### ISSUE TITLE
Data/*.hdf5

### ISSUE THREAD

**Issue by 0xdarkman** [NickKaparinos/Automated-Cryptocurrency-trading-using-Deep-RL#1]
Would you mind to share code to create datasets Data/*.hdf5 ?

**Comment by NickKaparinos** [comment]
You can probably very easily find crypto/ stock data online. They do not have to be in the hdf5 format necessarily. They should have the following columns in order to be used with my code:

['open', 'high', 'low', 'close']

**Comment by 0xdarkman** [comment]
Have you used 1min data with these 4 columns only?

**Comment by NickKaparinos** [comment]
I have experimented with 30min and 1H data, with hourly data resulting in optimal performance.

**Comment by 0xdarkman** [comment]
Ok. So I shall use hourly data and not 1 minute data. Thank you.
