### ISSUE TITLE
downtrend behaviour

### ISSUE THREAD

**Issue by dariuszkrynicki** [NickKaparinos/Automated-Cryptocurrency-trading-using-Deep-RL#4]
have you tried to add a boolean feature e.g. downtrend being true or false so the model is blocked from doing buy action or model is force to do sell action when bear flag is on?

the reason behing the question is: how to improve model behaviour and stop it from loosing portfolio value / trading when down trend is detected and more impornantly when sudden turbulence / sudden down spike occurs like in march 2020 or some sudden sells in december 2019.

any thoughts?

**Comment by NickKaparinos** [comment]
No, I have not experimented with anything like that. The reason is that the agent may be able to make profit even when the cryptos are trending down, because of the price fluctuations. However, ideas like that may have their place.

**Comment by dariuszkrynicki** [comment]
It works in uptrend but looses profits during downtrend hence I came with such an idea to either block it from trading during down trend OR by adding additional feature to see if model can learn from it.
